PEOPLE: fix missing company name leads to 404.
Mysterious error was found, when checkbox company was checked but
no company_name was provided.
`tidy_bytes': undefined method `empty?' for nil:NilClass (NoMethodError)
return string if string.empty? || string.ascii_only?
Problem, was that to_s function returned nil, which should never happen.